apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: serviceciscoapp
  name: serviceciscoapp
  namespace: ishrakk8s1
spec:
  ports:
  - name: 1234-80
    port: 1234
    protocol: TCP
    targetPort: 80
  selector:
    app: ishrakciscoapp
  type: NodePort
status:
  loadBalancer: {}
